// Code generated by goctl. DO NOT EDIT.
package types

type GetClusterNamespaceReq struct {
	ClusterId string `json:"cluster_id"`
	Namespace string `json:"namespace"`
}

type GetClusterNamespaceResp struct {
	Namespcace []string `json:"namespace"`
}
