// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/zeromicro/go-zero/rest"
	"net/http"

	clusterInfo "operator-manager/internal/handler/clusterInfo"
	"operator-manager/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EarlyCheckMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/clusters",
					Handler: clusterInfo.GetClusterNamespaceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getclusternamespace/list",
					Handler: clusterInfo.GetClusterNamespaceHandler(serverCtx),
				},
			}...,
		),
	)
}
